version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: appointments_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

  backend:
    build: ./src/backend
    container_name: backend_container
    restart: always
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: app_user
      DB_PASSWORD: app_password
      DB_NAME: appointments_db
      DB_PORT: 3306
    ports:
      - "5000:5000"
    networks:
      - app_network
    volumes:
      - ./src/backend:/app
      - /app/node_modules

volumes:
  mysql_data:

networks:
  app_network:
